default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: aleksandrakucharczyk_development

test:
  <<: *default
  adapter: postgresql
  database: aleksandrakucharczyk_test

production:
  <<: *default
