default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aleksandrakucharczyk_development

test:
  <<: *default
  database: aleksandrakucharczyk_test

production:
  <<: *default
  database: aleksandrakucharczyk_production
  username: aleksandrakucharczyk
  password: <%= ENV['ALEKSANDRAKUCHARCZYK_DATABASE_PASSWORD'] %>
